### PR TITLE
Adding some Docker automation goodness

### PR DESCRIPTION
**Pull request by scheerer**

### CODE REVIEW

**Comment by mtheoryx** [comment]
Does this make Docker a requirement of building/running the app?

**Comment by scheerer** [comment]
The running app will not pickup your file changes live due to a filesystem issue we need to figure out how to workaround when using Docker on Mac OSX.

**Comment by scheerer** [comment]
Well, not really... but... you'll have to change the app.js back to localhost for the mongo connection if you choose not to use Docker. My comment in the app.js about getting the host externalized via ENV vars would eliminate this issue however.

**Comment by mtheoryx** [comment]
Externalized vars would be solved by, perhaps, Gulp?

I created an issue to introduce Gulp to the app [here](https://github.com/CtrlShiftF11/TeamWare/issues/3), perhaps you could create one as well that details what vars you need?

**Comment by scheerer** [comment]
Of course they could, the purpose of this was 1 thing at a time

**Pull request closed without merging**
